### PR TITLE
Week 10 Day 1 hw

### PR DESCRIPTION
**Pull request by madeleinemila**
No live fishtank for me, pretended I was just the backend guy (made home page for convenience and because I wanted to see the handling of different symbols, accents, emojis etc)
Feedback always appreciated :)
Difficulty wasn't too hard, Twitter docs look good and gem makes it easy, time taken really just to digest that info

### CODE REVIEW

**Comment by madeleinemila** [comment]
Now added the Ruby SinglyLinkedList exercises. Found some of them really tricky, enjoyed hanging out in pry trying to get to the bottom of each one. Would love to know if my approaches are OK or if you know better ways.

**Comment by madeleinemila** [comment]
Now with a fibonacci recursion attempt :)

**Comment by madeleinemila** [comment]
Now with promises attempt.
Difficulty: lots. Find this really hard. I got the wait one working, although couldn't figure out how to make them work in a chain. Couldn't figure out the xhr one by myself so looked on SO and then tried to reproduce it but it only seems to catch errors so I'm missing something. Def something I'll be practising further down the track.

**Comment by JoshuaMcEvoy** [comment]
Hey Maddie, Sorry I kind of stopped checking this everyday as no one commits anything anymore. 
Your code is looking great. I love that you even added the << append function. You've definitely taken the right approach. 
You should be really proud at how much you have smashed this course. You're definitely going to be able to pick and choose which company you want to work in. They will all be lucky to have you :)

**Pull request merged**
