### PR TITLE
Homework week 4 day 5 - art and artist website

### PR DESCRIPTION
**Pull request by SamanthaCord**
Homework feedback each pull request:
How difficult did I find this? = it was ok, and learnt a lot about server caching and reading error messages
Was there anything I struggled with? = associations 
Is there anything I would like more info on? = not yet
Roughly how long did this take?= 8 hours, a lot of it styling things

### CODE REVIEW

**Comment by SamanthaCord** [comment]
How difficult did I find this? = Was ok
Was there anything I struggled with? = couldn't compare the guess against secret number to show a winning or loser message. Could only display both on screen
Is there anything I would like more info on? = no
Roughly how long did this take?= 5 hours

**Comment by SamanthaCord** [comment]
How difficult did I find this? = Rails part was ok, didn't have enough time to finish my styling
Was there anything I struggled with? = 
Is there anything I would like more info on? = no
Roughly how long did this take?= 5 hours

**Comment by SamanthaCord** [comment]
Homework week5 day3
How difficult did I find this? = was ok with joels code to refer to
Was there anything I struggled with? = no
Is there anything I would like more info on? = no
Roughly how long did this take?= 4 hours

**Comment by JoshuaMcEvoy** [comment]
Your last commit had over 2000 file!! Now you're a proper dev! I'm dizzy from going through them.

**Pull request merged**
